### ISSUE TITLE
ERROR parsing time "" as "2006"

### ISSUE THREAD

**Issue by uder** [github/gh-ost#747]
Hello everyone!

I'm trying to alter huge table (~250kk) on test server with gh-ost
# My Command:
gh-ost  \
--switch-to-rbr \
--verbose \
--user=root \
--ask-pass  \
--database=sp \
--table purchase_feedbacks \
--alter="CONVERT TO CHARACTER SET utf8mb4" \
--chunk-size=2000 \
--max-load=Threads_connected=20 \
--discard-foreign-keys \
--allow-on-master

# My Output:
2019-05-29 12:22:16 INFO starting gh-ost 1.0.48
2019-05-29 12:22:16 INFO Migrating `sp`.`purchase_feedbacks`
2019-05-29 12:22:16 INFO connection validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO User has SUPER, REPLICATION SLAVE privileges, and has ALL privileges on `sp`.*
2019-05-29 12:22:16 INFO binary logs validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO Restarting replication on 127.0.0.1:3306 to make sure binlog settings apply to replication thread
2019-05-29 12:22:16 INFO Inspector initiated on bkp02.100sp.ru:3306, version 8.0.15-5
2019-05-29 12:22:16 INFO Table found. Engine=InnoDB
2019-05-29 12:22:16 INFO Estimated number of rows via EXPLAIN: 23345250
2019-05-29 12:22:16 INFO Recursively searching for replication master
2019-05-29 12:22:16 INFO Master found to be bkp02.100sp.ru:3306
2019-05-29 12:22:16 INFO log_slave_updates validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO connection validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO Connecting binlog streamer at log_bin.000001:32218
[2019/05/29 12:22:16] [info] binlogsyncer.go:133 create BinlogSyncer with config {99999 mysql 127.0.0.1 3306 root    false false <nil> false UTC true 0 0s 0s 0 false}
[2019/05/29 12:22:16] [info] binlogsyncer.go:354 begin to sync binlog from position (log_bin.000001, 32218)
[2019/05/29 12:22:16] [info] binlogsyncer.go:203 register slave for master server 127.0.0.1:3306
[2019/05/29 12:22:16] [info] binlogsyncer.go:723 rotate to (log_bin.000001, 32218)
2019-05-29 12:22:16 INFO rotate to next log from log_bin.000001:0 to log_bin.000001
2019-05-29 12:22:16 INFO connection validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO connection validated on 127.0.0.1:3306
2019-05-29 12:22:16 INFO will use time_zone='SYSTEM' on applier
2019-05-29 12:22:16 INFO Examining table structure on applier
2019-05-29 12:22:16 INFO Applier initiated on bkp02.100sp.ru:3306, version 8.0.15-5
2019-05-29 12:22:16 INFO Dropping table `sp`.`_purchase_feedbacks_ghc`
2019-05-29 12:22:16 INFO Table dropped
2019-05-29 12:22:16 INFO Creating changelog table `sp`.`_purchase_feedbacks_ghc`
2019-05-29 12:22:17 INFO Changelog table created
2019-05-29 12:22:17 INFO Creating ghost table `sp`.`_purchase_feedbacks_gho`
2019-05-29 12:22:18 INFO Ghost table created
2019-05-29 12:22:18 INFO Altering ghost table `sp`.`_purchase_feedbacks_gho`
2019-05-29 12:22:19 INFO Ghost table altered
2019-05-29 12:22:19 INFO Intercepted changelog state GhostTableMigrated
2019-05-29 12:22:20 INFO Waiting for ghost table to be migrated. Current lag is 0s
2019-05-29 12:22:20 INFO Handled changelog state GhostTableMigrated
2019-05-29 12:22:20 INFO Chosen shared unique key is PRIMARY
2019-05-29 12:22:20 INFO Shared columns are fpid,pid,uid,rating,comment,org_work,good_quality,price,org_answer,recommendation,created,likes,moderation_status,megapurchase_id
,is_published,org_answered_at,updated_at,mid
2019-05-29 12:22:20 INFO Listening on unix socket file: /tmp/gh-ost.sp.purchase_feedbacks.sock
2019-05-29 12:22:20 INFO Migration min values: [18]                                                                                                                 [20/1821]
2019-05-29 12:22:20 INFO Migration max values: [26569645]
2019-05-29 12:22:20 INFO Waiting for first throttle metrics to be collected
**2019-05-29 12:22:20 ERROR parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"**
2019-05-29 12:22:20 INFO First throttle metrics collected
\# Migrating `sp`.`purchase_feedbacks`; Ghost table is `sp`.`_purchase_feedbacks_gho`
\# Migrating bkp02.100sp.ru:3306; inspecting bkp02.100sp.ru:3306; executing on bkp02.100sp.ru
\# Migration started at Wed May 29 12:22:16 +1000 2019
\# chunk-size: 2000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: Threads_connected=20; critical-load: ; nice-ratio: 0.000000
\# throttle-additional-flag-file: /tmp/gh-ost.throttle
\# Serving on unix socket: /tmp/gh-ost.sp.purchase_feedbacks.sock
2019-05-29 12:22:20 INFO Row copy complete
Copy: 0/23345250 0.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 0s(copy); streamer: log_bin.000001:34146; State: migrating; ETA: N/A
Copy: 0/0 100.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 0s(copy); streamer: log_bin.000001:34146; State: migrating; ETA: due
2019-05-29 12:22:20 INFO New table structure follows
```
  CREATE TABLE `_purchase_feedbacks_gho` (
  `fpid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(11) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `rating` enum('negative','neutral','positive','not_defined') DEFAULT NULL,
  `comment` mediumtext,
  `org_work` tinyint(3) unsigned DEFAULT NULL,
  `good_quality` tinyint(3) unsigned DEFAULT NULL,
  `price` tinyint(3) unsigned DEFAULT NULL,
  `org_answer` varchar(2048) DEFAULT NULL,
  `recommendation` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `likes` int(11) NOT NULL DEFAULT '0',
  `moderation_status` enum('clean','need_moderate','approved','rejected') NOT NULL DEFAULT 'clean',
  `megapurchase_id` int(10) unsigned DEFAULT NULL,
  `is_published` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `org_answered_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `mid` int(11) DEFAULT NULL,
  PRIMARY KEY (`fpid`),
  UNIQUE KEY `pid_uid` (`pid`,`uid`),
  KEY `uid` (`uid`),
  KEY `pid_comment_moderation_status` (`pid`,`comment`(1),`moderation_status`),
  KEY `megapurchase_published` (`megapurchase_id`,`is_published`,`created`),
  KEY `megapurchase_published_likes` (`megapurchase_id`,`is_published`,`likes`,`created`),
  KEY `fk_purchase_feedbacks_mid` (`mid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
[2019/05/29 12:22:20] [info] binlogsyncer.go:164 syncer is closing...
**[2019/05/29 12:22:20] [error] binlogstreamer.go:77 close sync with err: sync is been closing...**
2019-05-29 12:22:20 INFO Closed streamer connection. err=<nil>
2019-05-29 12:22:20 INFO Dropping table `sp`.`_purchase_feedbacks_ghc`
[2019/05/29 12:22:20] [info] binlogsyncer.go:179 syncer is closed
2019-05-29 12:22:20 INFO Table dropped
2019-05-29 12:22:20 INFO Dropping table `sp`.`_purchase_feedbacks_gho`
**2019-05-29 12:22:20 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist**
**2019-05-29 12:22:20 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist**
**2019-05-29 12:22:20 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist**
**2019-05-29 12:22:20 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist**
2019-05-29 12:22:20 INFO Table dropped
2019-05-29 12:22:20 INFO Done migrating `sp`.`purchase_feedbacks`
2019-05-29 12:22:20 INFO Removing socket file: /tmp/gh-ost.sp.purchase_feedbacks.sock
2019-05-29 12:22:20 INFO Tearing down inspector
2019-05-29 12:22:20 INFO Tearing down applier
2019-05-29 12:22:20 INFO Tearing down streamer
2019-05-29 12:22:20 INFO Tearing down throttler
\# Done

*Output was slightly changed. I've added some formatting for convinience*

I've get strange error (parsing time "" as "2006"). I've found some similar posts in inetrnet (one on this tracker) but that solutions doesn't help

Please help me found out what is the issue

**Comment by shlomi-noach** [comment]
This one is strange, indeed. Can you please run again eith `--debug --stack`?

The only relevant error is the `2006` one. The rest you can ignore (I agree they are bothersome; one is being fixes right now, the other some other time).

**Comment by uder** [comment]
Hello! 
Thanks for answer

gh-ost --switch-to-rbr --verbose --user=root --ask-pass  --database=sp --table purchase_feedbacks --alter="CONVERT TO CHARACTER SET utf8mb4" --chunk-
size=2000 --max-load=Threads_connected=20 --discard-foreign-keys --allow-on-master --debug --stack

# Output:
2019-05-31 08:16:55 INFO starting gh-ost 1.0.48
2019-05-31 08:16:55 INFO Migrating `sp`.`purchase_feedbacks`
2019-05-31 08:16:55 INFO connection validated on 127.0.0.1:3306
2019-05-31 08:16:55 INFO User has SUPER, REPLICATION SLAVE privileges, and has ALL privileges on `sp`.*
2019-05-31 08:16:55 INFO binary logs validated on 127.0.0.1:3306
2019-05-31 08:16:55 INFO Restarting replication on 127.0.0.1:3306 to make sure binlog settings apply to replication thread
2019-05-31 08:16:55 INFO Inspector initiated on bkp02.100sp.ru:3306, version 8.0.15-5
2019-05-31 08:16:55 INFO Table found. Engine=InnoDB
2019-05-31 08:16:55 DEBUG Estimated number of rows via STATUS: 23345250
2019-05-31 08:16:55 DEBUG Foreign keys found and will be dropped, as per given --discard-foreign-keys flag
2019-05-31 08:16:55 DEBUG Validated no triggers exist on table
2019-05-31 08:16:55 INFO Estimated number of rows via EXPLAIN: 23345250
2019-05-31 08:16:55 DEBUG Potential unique keys in purchase_feedbacks: [PRIMARY (auto_increment): [fpid]; has nullable: false pid_uid: [pid uid]; has nullable: true]
2019-05-31 08:16:55 INFO Recursively searching for replication master
2019-05-31 08:16:55 DEBUG Looking for master on 127.0.0.1:3306
2019-05-31 08:16:55 INFO Master found to be bkp02.100sp.ru:3306
2019-05-31 08:16:55 INFO log_slave_updates validated on 127.0.0.1:3306
2019-05-31 08:16:55 INFO connection validated on 127.0.0.1:3306
2019-05-31 08:16:55 DEBUG Streamer binlog coordinates: log_bin.000001:44784
2019-05-31 08:16:55 INFO Connecting binlog streamer at log_bin.000001:44784
[2019/05/31 08:16:55] [info] binlogsyncer.go:133 create BinlogSyncer with config {99999 mysql 127.0.0.1 3306 root    false false <nil> false UTC true 0 0s 0s 0 false}
[2019/05/31 08:16:55] [info] binlogsyncer.go:354 begin to sync binlog from position (log_bin.000001, 44784)
[2019/05/31 08:16:55] [info] binlogsyncer.go:203 register slave for master server 127.0.0.1:3306
2019-05-31 08:16:55 DEBUG Beginning streaming
[2019/05/31 08:16:55] [info] binlogsyncer.go:723 rotate to (log_bin.000001, 44784)
2019-05-31 08:16:55 INFO rotate to next log from log_bin.000001:0 to log_bin.000001
2019-05-31 08:16:55 INFO connection validated on 127.0.0.1:3306
2019-05-31 08:16:55 INFO connection validated on 127.0.0.1:3306
2019-05-31 08:16:55 INFO will use time_zone='SYSTEM' on applier
2019-05-31 08:16:55 INFO Examining table structure on applier
2019-05-31 08:16:55 INFO Applier initiated on bkp02.100sp.ru:3306, version 8.0.15-5
2019-05-31 08:16:55 INFO Dropping table `sp`.`_purchase_feedbacks_ghc`
2019-05-31 08:16:55 INFO Table dropped
2019-05-31 08:16:55 INFO Creating changelog table `sp`.`_purchase_feedbacks_ghc`
2019-05-31 08:16:55 INFO Changelog table created
2019-05-31 08:16:55 INFO Creating ghost table `sp`.`_purchase_feedbacks_gho`
2019-05-31 08:16:56 INFO Ghost table created
2019-05-31 08:16:56 INFO Altering ghost table `sp`.`_purchase_feedbacks_gho`
2019-05-31 08:16:56 DEBUG ALTER statement: alter /* gh-ost */ table `sp`.`_purchase_feedbacks_gho` CONVERT TO CHARACTER SET utf8mb4
2019-05-31 08:16:57 INFO Ghost table altered
2019-05-31 08:16:57 INFO Intercepted changelog state GhostTableMigrated
2019-05-31 08:16:57 INFO Waiting for ghost table to be migrated. Current lag is 0s
2019-05-31 08:16:57 DEBUG ghost table migrated
2019-05-31 08:16:57 INFO Handled changelog state GhostTableMigrated
2019-05-31 08:16:57 DEBUG Potential unique keys in _purchase_feedbacks_gho: [PRIMARY (auto_increment): [fpid]; has nullable: false pid_uid: [pid uid]; has nullable: true]
2019-05-31 08:16:57 INFO Chosen shared unique key is PRIMARY
2019-05-31 08:16:57 INFO Shared columns are fpid,pid,uid,rating,comment,org_work,good_quality,price,org_answer,recommendation,created,likes,moderation_status,megapurchase_i
d,is_published,org_answered_at,updated_at,mid
2019-05-31 08:16:57 INFO Listening on unix socket file: /tmp/gh-ost.sp.purchase_feedbacks.sock
2019-05-31 08:16:57 DEBUG Reading migration range according to key: PRIMARY
2019-05-31 08:16:57 INFO Migration min values: [18]
2019-05-31 08:16:57 DEBUG Reading migration range according to key: PRIMARY
2019-05-31 08:16:57 INFO Migration max values: [26569645]
2019-05-31 08:16:57 INFO Waiting for first throttle metrics to be collected
2019-05-31 08:16:57 ERROR parsing time "" as "2006-01-02T15:04:05.999999999Z07:00": cannot parse "" as "2006"
goroutine 61 [running]:
runtime/debug.Stack(0x6d, 0x180, 0xc42007c780)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7ebd00, 0xc42008c9b0, 0x7ebd00, 0xc42008c9b0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xe9
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7ebd00, 0xc42008c9b0, 0x0, 0x7ebd00)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/go/logic.(*Throttler).parseChangelogHeartbeat(0xc420377480, 0x0, 0x0, 0x0, 0x0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/throttler.go:123 +0x5b
github.com/github/gh-ost/go/logic.(*Throttler).collectReplicationLag.func1(0x740780, 0xc420057cd0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/throttler.go:153 +0x130
github.com/github/gh-ost/go/logic.(*Throttler).collectReplicationLag(0xc420377480, 0xc420070070)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/throttler.go:159 +0x65
created by github.com/github/gh-ost/go/logic.(*Throttler).initiateThrottlerCollection
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/throttler.go:398 +0x4d
2019-05-31 08:16:57 INFO First throttle metrics collected
2019-05-31 08:16:57 DEBUG Operating until row copy is complete
\# Migrating `sp`.`purchase_feedbacks`; Ghost table is `sp`.`_purchase_feedbacks_gho`
2019-05-31 08:16:57 DEBUG Noop operation; not really executing write funcs
\# Migrating bkp02.100sp.ru:3306; inspecting bkp02.100sp.ru:3306; executing on bkp02.100sp.ru
\# Migration started at Fri May 31 08:16:55 +1000 2019
2019-05-31 08:16:57 DEBUG Noop operation; not really copying data
\# chunk-size: 2000; max-lag-millis: 1500ms; dml-batch-size: 10; max-load: Threads_connected=20; critical-load: ; nice-ratio: 0.000000
2019-05-31 08:16:57 INFO Row copy complete
\# throttle-additional-flag-file: /tmp/gh-ost.throttle
\# Serving on unix socket: /tmp/gh-ost.sp.purchase_feedbacks.sock
Copy: 0/0 100.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 0s(copy); streamer: log_bin.000001:46712; State: migrating; ETA: due
2019-05-31 08:16:57 DEBUG Noop operation; not really swapping tables
2019-05-31 08:16:57 INFO New table structure follows
```
CREATE TABLE `_purchase_feedbacks_gho` (
  `fpid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(11) DEFAULT NULL,
  `uid` int(11) DEFAULT NULL,
  `rating` enum('negative','neutral','positive','not_defined') DEFAULT NULL,
  `comment` mediumtext,
  `org_work` tinyint(3) unsigned DEFAULT NULL,
  `good_quality` tinyint(3) unsigned DEFAULT NULL,
  `price` tinyint(3) unsigned DEFAULT NULL,
  `org_answer` varchar(2048) DEFAULT NULL,
  `recommendation` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `likes` int(11) NOT NULL DEFAULT '0',
  `moderation_status` enum('clean','need_moderate','approved','rejected') NOT NULL DEFAULT 'clean',
  `megapurchase_id` int(10) unsigned DEFAULT NULL,
  `is_published` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `org_answered_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `mid` int(11) DEFAULT NULL,
  PRIMARY KEY (`fpid`),
  UNIQUE KEY `pid_uid` (`pid`,`uid`),
  KEY `uid` (`uid`),
  KEY `pid_comment_moderation_status` (`pid`,`comment`(1),`moderation_status`),
  KEY `megapurchase_published` (`megapurchase_id`,`is_published`,`created`),
  KEY `megapurchase_published_likes` (`megapurchase_id`,`is_published`,`likes`,`created`),
  KEY `fk_purchase_feedbacks_mid` (`mid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```
[2019/05/31 08:16:57] [info] binlogsyncer.go:164 syncer is closing...
[2019/05/31 08:16:57] [error] binlogstreamer.go:77 close sync with err: sync is been closing...
2019-05-31 08:16:57 DEBUG Done streaming
Copy: 0/23345250 0.0%; Applied: 0; Backlog: 0/1000; Time: 2s(total), 0s(copy); streamer: log_bin.000001:46712; State: migrating; ETA: N/A
2019-05-31 08:16:57 INFO Closed streamer connection. err=<nil>
[2019/05/31 08:16:57] [info] binlogsyncer.go:179 syncer is closed
2019-05-31 08:16:57 INFO Dropping table `sp`.`_purchase_feedbacks_ghc`
2019-05-31 08:16:58 INFO Table dropped
2019-05-31 08:16:58 INFO Dropping table `sp`.`_purchase_feedbacks_gho`
2019-05-31 08:16:58 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist
goroutine 72 [running]:
runtime/debug.Stack(0x56, 0x160, 0xc4201aa580)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7eb6e0, 0xc4201978c0, 0x7eb6e0, 0xc4201978c0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xe9
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7eb6e0, 0xc4201978c0, 0xc1, 0xc4202bfea0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils.ExecNoPrepare(0xc4200990e0, 0xc4203e6000, 0xc1, 0xc4202bfea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils/sqlutils.go:283 +0x12a
github.com/github/gh-ost/go/logic.(*Applier).WriteChangelog(0xc4201fe600, 0x7987fb, 0x9, 0xc4202120f0, 0x23, 0xc4202120f0, 0x23, 0xc4202bff30, 0xc4202bff48)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:292 +0x307
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat.func1(0xc420156000, 0xc4202bff00)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:313 +0x9f
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat(0xc4201fe600)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:336 +0x139
created by github.com/github/gh-ost/go/logic.(*Migrator).initiateApplier
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/migrator.go:1071 +0x1f5
2019-05-31 08:16:58 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist
goroutine 72 [running]:
runtime/debug.Stack(0x56, 0x100, 0xc4201aa640)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7eb6e0, 0xc4201978e0, 0x7eb6e0, 0xc4201978e0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xe9
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7eb6e0, 0xc4201978e0, 0xc1, 0xc4202bfea0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils.ExecNoPrepare(0xc4200990e0, 0xc4203d60d0, 0xc1, 0xc4202bfea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils/sqlutils.go:283 +0x12a
github.com/github/gh-ost/go/logic.(*Applier).WriteChangelog(0xc4201fe600, 0x7987fb, 0x9, 0xc4201a82d0, 0x23, 0xc4201a82d0, 0x23, 0xc4202bff30, 0xc4202bff48)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:292 +0x307
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat.func1(0xc420156000, 0xc4202bff00)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:313 +0x9f
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat(0xc4201fe600)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:336 +0x139
created by github.com/github/gh-ost/go/logic.(*Migrator).initiateApplier
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/migrator.go:1071 +0x1f5
2019-05-31 08:16:58 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist
goroutine 72 [running]:
runtime/debug.Stack(0x56, 0x160, 0xc4201aa700)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7eb6e0, 0xc420197900, 0x7eb6e0, 0xc420197900)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xe9
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7eb6e0, 0xc420197900, 0xc1, 0xc4202bfea0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils.ExecNoPrepare(0xc4200990e0, 0xc4203d61a0, 0xc1, 0xc4202bfea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils/sqlutils.go:283 +0x12a
github.com/github/gh-ost/go/logic.(*Applier).WriteChangelog(0xc4201fe600, 0x7987fb, 0x9, 0xc4201a8330, 0x23, 0xc4201a8330, 0x23, 0xc4202bff30, 0xc4202bff48)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:292 +0x307
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat.func1(0xc420156000, 0xc4202bff00)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:313 +0x9f
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat(0xc4201fe600)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:336 +0x139
created by github.com/github/gh-ost/go/logic.(*Migrator).initiateApplier
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/migrator.go:1071 +0x1f5
2019-05-31 08:16:58 ERROR Error 1146: Table 'sp._purchase_feedbacks_ghc' doesn't exist
goroutine 72 [running]:
runtime/debug.Stack(0x56, 0x100, 0xc4202e2440)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.logErrorEntry(0x2, 0x7eb6e0, 0xc42038ca60, 0x7eb6e0, 0xc42038ca60)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:178 +0xe9
github.com/github/gh-ost/vendor/github.com/outbrain/golib/log.Errore(0x7eb6e0, 0xc42038ca60, 0xc1, 0xc4202bfea0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/log/log.go:224 +0x3e
github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils.ExecNoPrepare(0xc4200990e0, 0xc420300340, 0xc1, 0xc4202bfea0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/vendor/github.com/outbrain/golib/sqlutils/sqlutils.go:283 +0x12a
github.com/github/gh-ost/go/logic.(*Applier).WriteChangelog(0xc4201fe600, 0x7987fb, 0x9, 0xc4202de270, 0x23, 0xc4202de270, 0x23, 0xc4202bff30, 0xc4202bff48)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:292 +0x307
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat.func1(0xc420156000, 0xc4202bff00)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:313 +0x9f
github.com/github/gh-ost/go/logic.(*Applier).InitiateHeartbeat(0xc4201fe600)
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/applier.go:336 +0x139
created by github.com/github/gh-ost/go/logic.(*Migrator).initiateApplier
        /home/shlomi-noach/go/src/github.com/github/gh-ost/go/logic/migrator.go:1071 +0x1f5
2019-05-31 08:16:58 INFO Table dropped
2019-05-31 08:16:58 INFO Done migrating `sp`.`purchase_feedbacks`
2019-05-31 08:16:58 INFO Removing socket file: /tmp/gh-ost.sp.purchase_feedbacks.sock
2019-05-31 08:16:58 INFO Tearing down inspector
2019-05-31 08:16:58 INFO Tearing down applier
2019-05-31 08:16:58 DEBUG Tearing down...
2019-05-31 08:16:58 INFO Tearing down streamer
2019-05-31 08:16:58 INFO Tearing down throttler
2019-05-31 08:16:58 DEBUG Tearing down...
\# Done

**Comment by shlomi-noach** [comment]
OK, thank you. This error is safe to ignore and has to do with internal heartbeat collection for purposes of throttling. I should fix it, of course, but meanwhile please carry on.

**Comment by uder** [comment]
Thanks for reply! 

Unfortunately, I can't igonre it, cause I can't get my alter done.

Is there any workarounds?

**Comment by shlomi-noach** [comment]
Hmmm I think something else is at hand. I'm bothered by:
```
Copy: 0/23345250 0.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 0s(copy); streamer: log_bin.000001:34146; State: migrating; ETA: N/A
Copy: 0/0 100.0%; Applied: 0; Backlog: 0/1000; Time: 3s(total), 0s(copy); streamer: log_bin.000001:34146; State: migrating; ETA: due
```
why would rowcount jump from `23345250` to `0`?

I assume that the table is non-empty.

Could you possibly upload a complete log file?

**Comment by uder** [comment]
Thanks for reply!
I was not pay attention, I'm sorry. Alter was not started, becouse i've missed --execute. 

Errors still here. But whatever, I've successfuly performed my alter.
Thank you very much for your assitance!

**Comment by shlomi-noach** [comment]
haha cool.
